before_script:
 - git fetch --unshallow # we need a full clone for tests
 - git config --global user.email "you@example.com"
 - git config --global user.name "Your Name"
script: "bundle exec rake"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2
