before_script:
 - git fetch --unshallow # we need a full clone for tests
 - git config --global user.email "you@example.com"
 - git config --global user.name "Your Name"
before_install:
 - gem update bundler
script: "bundle exec rake"
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
